project/urls.py
from django.contrib import admin
from django.urls import path, include
from taller import views

urlpatterns = [
    path('', include('taller.urls')),
    path('admin/', admin.site.urls),
    path('', include("security.urls")),
]

taller/urls.py
from django.urls import path

from . import views

app_name = "taller"
urlpatterns = [
    # # ex: /polls/
    # path("", views.index, name="index"),
    # # ex: /polls/5/
    # path("polls/<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("polls/<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("polls/<int:question_id>/vote/", views.vote, name="vote"),
    
    
    # path("polls/<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("polls/<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("polls/<int:question_id>/vote/", views.vote, name="vote"),
    
    # path("", views.IndexView.as_view(), name="index"),
    path("", views.index, name="index"),
    path("taller/registro", views.RegistroIndexView.as_view(), name="registro"),
    path('taller/registro-recepcionados', views.registro_recepcionados, name='registro-recepcionados'),
    path('taller/registro-asignados', views.registro_asignados, name='registro-asignados'),
    path('taller/registro-en-proceso', views.registro_en_proceso, name='registro-en-proceso'),
    path('taller/registro-finalizados', views.registro_finalizados, name='registro-finalizados'),
    
    # path('taller/prioridades/', views.prioridad_list_view, name='prioridades-list'),
    path('taller/prioridades/', views.PrioridadListView.as_view(), name='prioridades-list'),
    path('taller/crear-prioridad/', views.create_prioridad_view, name='create-prioridad'),
    
    path('taller/equipos/', views.EquipoListView.as_view(), name='equipos-list'),
    path('taller/crear-equipo/', views.create_equipo_view, name='create-equipo'),
    
    path('taller/crear-registro/', views.create_registro_view, name='create-registro'),
    path('taller/asignar-trabajo/<int:id>/', views.asignar_trabajo_view, name='asignar-trabajo'),
    path('taller/evaluar-trabajo/<int:id>/', views.evaluar_trabajo_view, name='evaluar-trabajo'),
    path('taller/finalizar-trabajo/<int:id>/', views.finalizar_trabajo_view, name='finalizar-trabajo'),
    path('taller/verificar-trabajo/<int:id>/', views.verificar_trabajo_view, name='verificar-trabajo'),
    
    # asistentes para reportes
    path('taller/reporte-x-fecha/<str:reporte>/', views.date_selector, name='reporte-x-fecha'),
    path('taller/reporte-x-entidad/<str:reporte>/', views.entidad_selector, name='reporte-x-entidad'),
    path('taller/reporte-x-prioridad/<str:reporte>/', views.prioridad_selector, name='reporte-x-prioridad'),
    path('taller/reporte-x-especialista/<str:reporte>/', views.especialista_selector, name='reporte-x-especialista'),
    path('taller/reporte-x-estado/<str:reporte>/', views.estado_selector, name='reporte-x-estado'),
    
    # Gráficas:
    path('taller/graficas/detalle-x-entidad/', views.grafica_detalle_x_entidad, name='graficas-detalle-x-entidad'),
    path('taller/graficas/total-x-entidad/', views.grafica_total_x_entidad, name='graficas-total-x-entidad'),
]

taller/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

# -----------------------------------------------
# Estas son las clases para la gestión del taller
# -----------------------------------------------

class TipoProblema(models.Model):
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table_comment = "Clasificación de tipos de problema"

    def __str__(self):
        return self.nombre

class TipoEquipo(models.Model):
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table_comment = "Clasificación de tipos de equipo"

    def __str__(self):
        return self.nombre
    
class Prioridad(models.Model):
    nombre = models.CharField(max_length=50)
    class Meta:
        db_table_comment = "Clasificación de Prioridad"

    def __str__(self):
        return self.nombre

class Equipo(models.Model):
    nombre = models.CharField(max_length=50)
    marca = models.CharField(max_length=50)
    modelo = models.CharField(max_length=50)
    tipo = models.ForeignKey(TipoEquipo, on_delete=models.CASCADE)
    inventario = models.CharField(max_length=20)
    class Meta:
        db_table_comment = "Detalles del equipo"

    def __str__(self):
        return self.inventario

class Especialista(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()
    class Meta:
        db_table_comment = "Especialista"

    def __str__(self):
        return self.nombre
    
class Entidad(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField(blank=True, null=True)
    direccion = models.CharField(max_length=100)
    telefono = models.CharField(max_length=12)
    class Meta:
        db_table_comment = "detalles de la Entidad"

    def __str__(self):
        return self.nombre


class Registro(models.Model):
    ESTADOS = [
        ("RECEPCIONADO", "Recepcionado"),
        ("ASIGNADO", "Asignado"),
        ("EVALUADO", "Evaluado"),
        ("EN_PROCESO", "En proceso"),
        ("FINALIZADO", "Finalizado"),
    ]
    
    equipo = models.ForeignKey(Equipo, on_delete=models.CASCADE)
    nombre_responsable = models.CharField(max_length=100)
    telefono_responsable = models.CharField(max_length=12)
    fecha_entrada = models.DateField()
    entidad = models.ForeignKey(Entidad, on_delete=models.CASCADE)
    problema_reportado = models.TextField()
    prioridad = models.ForeignKey(Prioridad, on_delete=models.CASCADE)
    estado = models.CharField(max_length=20, choices=ESTADOS,default="RECEPCIONADO")
    
    especialista = models.ForeignKey(Especialista, on_delete=models.SET_NULL, null=True)
    problema_real = models.TextField(blank=True, null=True)
    tipo_de_problema = models.ForeignKey(TipoProblema, on_delete=models.SET_NULL, null=True)
    
    solucionado = models.BooleanField(default=False)
    observaciones = models.TextField(blank=True, null=True)
    fecha_salida = models.DateField(blank=True, null=True)
    
    verificado = models.BooleanField(default=False)
    verificacion = models.TextField(blank=True, null=True)
    fecha_verificacion = models.DateField(blank=True, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Registro de {self.equipo.nombre} {self.equipo.modelo} - Responsable: {self.nombre_responsable}"

taller/views.py
from django.db.models import F, Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView
from django.db.models.functions import ExtractMonth
from calendar import month_name
import locale
from django.contrib.auth.decorators import login_required

from .models import Choice, Question, Registro, Prioridad, Entidad, Especialista, Equipo
from .forms import *

# Create your views here.

# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "latest_question_list"

#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Question.objects.order_by("-pub_date")[:5]

@login_required(login_url="/login/")
def index(request):
    title = f'Estado general del taller'
    
    total_registro_list = (Registro.objects
          .values('entidad__nombre')  # Group by entidad
          .annotate(ecount=Count('entidad'))  # Count registers for each entidad
          .order_by('-ecount')  # Optional: Ensure correct sorting
          )[:15]
    entidad_nombres = total_registro_list.values_list('entidad__nombre', flat=True)
    entidad_nombres = list(entidad_nombres)
    ecount_values = total_registro_list.values_list('ecount', flat=True)
    ecount_values = list(ecount_values)
    
    registros_x_estado_list = (Registro.objects
          .values('estado')
          .annotate(estcount=Count('estado'))
          )
    
    estado_nombres = registros_x_estado_list.values_list('estado', flat=True)
    estado_nombres = list(estado_nombres)
    estcount_values = registros_x_estado_list.values_list('estcount', flat=True)
    estcount_values = list(estcount_values)
    
    solucionados = Registro.objects.filter(solucionado=True).count()
    no_solucionados = Registro.objects.filter(solucionado=False).count()
    total_registros = Registro.objects.count()
    
    registros_por_mes = (Registro.objects
                     .annotate(mes=ExtractMonth('fecha_entrada'))
                     .values('mes')
                     .annotate(total_registros=Count('id'))
                     .order_by('mes'))
    locale.setlocale(locale.LC_TIME, 'es_ES.utf8')
    meses_en_espanol = {i: month_name[i] for i in range(1, 13)}
    resultados_registros_por_mes = [{'mes': meses_en_espanol[registro['mes']], 'total_registros': registro['total_registros']}
                                    for registro in registros_por_mes]
    
    # total_registros_x_mes = resultados_registros_por_mes.values_list('total_registros', flat=True)
    # total_registros_x_mes = list(total_registros_x_mes)
    # meses = resultados_registros_por_mes.values_list('mes', flat=True)
    # meses = list(meses)
    
    meses = [entry['mes'] for entry in resultados_registros_por_mes]
    total_registros_x_mes = [entry['total_registros'] for entry in resultados_registros_por_mes]
    
    
    context = {
        'title': title,
        'entidades': entidad_nombres,
        'totalregistros': ecount_values,
        'estados': estado_nombres,
        'estcount': estcount_values,
        'solucionados': solucionados,
        'no_solucionados': no_solucionados,
        'total_registros': total_registros,
        'total_registros_x_mes': total_registros_x_mes,
        'meses': meses,
        }
    return render(request, 'taller/index.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("taller:results", args=(question.id,)))


class RegistroIndexView(generic.ListView):
    model = Registro
    template_name = "taller/registro.html"
    
    # def get_queryset(self):
    #     queryset = Registro.objects.all()
    #     return queryset.order_by('fecha_entrada')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registro de recepciones'
        return context


class PrioridadListView(generic.ListView):
    model = Prioridad
    template_name = "taller/prioridades_list.html"

class EquipoListView(generic.ListView):
    model = Equipo
    template_name = "taller/equipos_list.html"

@login_required(login_url="/login/")
def create_prioridad_view(request):
    if request.method == 'POST':
        form = CreatePrioridadForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:prioridades-list'))
    else:
        form = CreatePrioridadForm()
    context = {'form': form}
    return render(request, 'taller/create_prioridad.html', context)

@login_required(login_url="/login/")
def create_equipo_view(request):
    if request.method == 'POST':
        form = CreateEquipoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:equipos-list'))
    else:
        form = CreateEquipoForm()
    context = {'form': form}
    return render(request, 'taller/create_equipo.html', context)

@login_required(login_url="/login/")
def create_registro_view(request):
    if request.method == 'POST':
        form = CreateRegistroForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:registro'))
    else:
        form = CreateRegistroForm()
    context = {'form': form}
    return render(request, 'taller/create_registro.html', context)

@login_required(login_url="/login/")
def asignar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = AsignaTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'ASIGNADO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-asignados'))
    else:
        form = AsignaTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/asigna_trabajo.html', context)

@login_required(login_url="/login/")
def evaluar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = EvaluaTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'EN_PROCESO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-en-proceso'))
    else:
        form = EvaluaTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/evaluar_trabajo.html', context)

@login_required(login_url="/login/")
def finalizar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = FinalizarTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'FINALIZADO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-finalizados'))
    else:
        form = FinalizarTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/finalizar_trabajo.html', context)

@login_required(login_url="/login/")
def verificar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = VerificarTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.verificado = True
            registro.save(update_fields=['verificado'])
            return HttpResponseRedirect(reverse('taller:registro-finalizados'))
    else:
        form = VerificarTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/verificar_trabajo.html', context)

@login_required(login_url="/login/")
def date_selector(request, reporte=None):
    if request.method == 'POST':
        fecha_inicial=request.POST['fecha_inicial']
        fecha_final=request.POST['fecha_final']
        if reporte == 'registro':
            title = f'Registro de recepciones desde {fecha_inicial}, hasta {fecha_inicial}'
            registro_list = Registro.objects.filter(fecha_entrada__range=(fecha_inicial, fecha_final))
            context = {
                'title': title,
                'registro_list': registro_list,
                }
            return render(request, 'taller/registro.html', context)
        
        if reporte == 'indicadores':
            title = f'indicadores {fecha_inicial}, hasta {fecha_inicial}'
            pass
        
    context = {}
    return render(request, 'wizards/date_selector.html', context)

@login_required(login_url="/login/")

taller/templates/wizards/date_selector.html
{% extends "frontend.html" %}

{% block content %}

<div class="d-flex justify-content-center h-100 mt-3">
  <div class="card">
    <div class="card-header text-center">
      <h4>Seleccionar Fecha</h4>
    </div>
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
          <label>Fecha inicial</label>
          <input type="date" name="fecha_inicial" class="form-control" required autofocus>
        </div>
        <div class="form-group mb-2">
          <label>Fecha final</label>
          <input type="date" name="fecha_final" class="form-control" required>
        </div>
        <div class="form-group text-center mt-2">
          <button type="submit" class="btn btn-primary btn-block">Ok</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

taller/templates/wizards/entidad_selector.html
{% extends "frontend.html" %}

{% block content %}

<div class="d-flex justify-content-center h-100 mt-3">
  <div class="card">
    <div class="card-header text-center">
      <h4>Seleccionar Entidad</h4>
    </div>
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
          <label>Entidad</label>
          <select name="entidad_id" id="entidad_id" class="form-control" required autofocus>
            <option value="">Seleccionar entidad</option>
            {% for entidad in entidad_list %}
              <option value="{{entidad.id}}">{{entidad.nombre}}</option>
            {% endfor %}
          </select>
        </div>


        <div class="form-group text-center mt-2">
          <button type="submit" class="btn btn-primary btn-block">Ok</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

taller/templates/wizards/especialista_selector.html
{% extends "frontend.html" %}

{% block content %}

<div class="d-flex justify-content-center h-100 mt-3">
  <div class="card">
    <div class="card-header text-center">
      <h4>Seleccionar Especialista</h4>
    </div>
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
          <label>especialista</label>
          <select name="especialista_id" id="especialista_id" class="form-control" required autofocus>
            <option value="">Seleccionar Especialista</option>
            {% for especialista in especialista_list %}
              <option value="{{especialista.id}}">{{especialista.nombre}}</option>
            {% endfor %}
          </select>
        </div>


        <div class="form-group text-center mt-2">
          <button type="submit" class="btn btn-primary btn-block">Ok</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

taller/templates/wizards/estado_selector.html
{% extends "frontend.html" %}

{% block content %}

<div class="d-flex justify-content-center h-100 mt-3">
  <div class="card">
    <div class="card-header text-center">
      <h4>Seleccionar Estado</h4>
    </div>
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
          <label>estado</label>
          <select name="estado_id" id="estado_id" class="form-control" required autofocus>
            <option value="">Seleccionar Estado</option>
            {% for estado in estado_list %}
              <option value="{{estado.id}}">{{estado.nombre}}</option>
            {% endfor %}
          </select>
        </div>


        <div class="form-group text-center mt-2">
          <button type="submit" class="btn btn-primary btn-block">Ok</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}

taller/templates/wizards/prioridad_selector.html
{% extends "frontend.html" %}

{% block content %}

<div class="d-flex justify-content-center h-100 mt-3">
  <div class="card">
    <div class="card-header text-center">
      <h4>Seleccionar Prioridad</h4>
    </div>
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="form-group mb-2">
          <label>prioridad</label>
          <select name="prioridad_id" id="prioridad_id" class="form-control" required autofocus>
            <option value="">Seleccionar Prioridad</option>
            {% for prioridad in prioridad_list %}
              <option value="{{prioridad.id}}">{{prioridad.nombre}}</option>
            {% endfor %}
          </select>
        </div>


        <div class="form-group text-center mt-2">
          <button type="submit" class="btn btn-primary btn-block">Ok</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}