project/urls.py
from django.contrib import admin
from django.urls import path, include
from taller import views

urlpatterns = [
    path('', include('taller.urls')),
    path('admin/', admin.site.urls),
    path('', include("security.urls")),
]

security/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

from . import views

app_name = 'security'
urlpatterns = [
    path('login/',LoginView.as_view(template_name='login.html'),name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

taller/urls.py
from django.urls import path

from . import views

app_name = "taller"
urlpatterns = [
    # # ex: /polls/
    # path("", views.index, name="index"),
    # # ex: /polls/5/
    # path("polls/<int:question_id>/", views.detail, name="detail"),
    # # ex: /polls/5/results/
    # path("polls/<int:question_id>/results/", views.results, name="results"),
    # # ex: /polls/5/vote/
    # path("polls/<int:question_id>/vote/", views.vote, name="vote"),
    
    
    # path("polls/<int:pk>/", views.DetailView.as_view(), name="detail"),
    # path("polls/<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    # path("polls/<int:question_id>/vote/", views.vote, name="vote"),
    
    # path("", views.IndexView.as_view(), name="index"),
    path("", views.index, name="index"),
    path("taller/registro", views.RegistroIndexView.as_view(), name="registro"),
    path('taller/registro-recepcionados', views.registro_recepcionados, name='registro-recepcionados'),
    path('taller/registro-asignados', views.registro_asignados, name='registro-asignados'),
    path('taller/registro-en-proceso', views.registro_en_proceso, name='registro-en-proceso'),
    path('taller/registro-finalizados', views.registro_finalizados, name='registro-finalizados'),
    
    # path('taller/prioridades/', views.prioridad_list_view, name='prioridades-list'),
    path('taller/prioridades/', views.PrioridadListView.as_view(), name='prioridades-list'),
    path('taller/crear-prioridad/', views.create_prioridad_view, name='create-prioridad'),
    
    path('taller/equipos/', views.EquipoListView.as_view(), name='equipos-list'),
    path('taller/crear-equipo/', views.create_equipo_view, name='create-equipo'),
    
    path('taller/crear-registro/', views.create_registro_view, name='create-registro'),
    path('taller/asignar-trabajo/<int:id>/', views.asignar_trabajo_view, name='asignar-trabajo'),
    path('taller/evaluar-trabajo/<int:id>/', views.evaluar_trabajo_view, name='evaluar-trabajo'),
    path('taller/finalizar-trabajo/<int:id>/', views.finalizar_trabajo_view, name='finalizar-trabajo'),
    path('taller/verificar-trabajo/<int:id>/', views.verificar_trabajo_view, name='verificar-trabajo'),
    
    # asistentes para reportes
    path('taller/reporte-x-fecha/<str:reporte>/', views.date_selector, name='reporte-x-fecha'),
    path('taller/reporte-x-entidad/<str:reporte>/', views.entidad_selector, name='reporte-x-entidad'),
    path('taller/reporte-x-prioridad/<str:reporte>/', views.prioridad_selector, name='reporte-x-prioridad'),
    path('taller/reporte-x-especialista/<str:reporte>/', views.especialista_selector, name='reporte-x-especialista'),
    path('taller/reporte-x-estado/<str:reporte>/', views.estado_selector, name='reporte-x-estado'),
    
    # Gráficas:
    path('taller/graficas/detalle-x-entidad/', views.grafica_detalle_x_entidad, name='graficas-detalle-x-entidad'),
    path('taller/graficas/total-x-entidad/', views.grafica_total_x_entidad, name='graficas-total-x-entidad'),
]

taller/forms.py
from django import forms
from .models import Registro, Prioridad, Equipo

class DateInput(forms.DateInput):
    input_type = 'date'

class CreateRegistroForm(forms.ModelForm):
  class Meta:
    model = Registro
    fields = ['equipo', 
              'nombre_responsable', 
              'telefono_responsable',
              'fecha_entrada',
              'entidad',
              'problema_reportado',
              'prioridad'
              ]
    
    widgets = {
            'fecha_entrada': DateInput(),
            }

class AsignaTrabajoForm(forms.ModelForm):
  class Meta:
    model = Registro
    fields = ['especialista']

class EvaluaTrabajoForm(forms.ModelForm):
  class Meta:
    model = Registro
    fields = ['problema_real','tipo_de_problema']
    
class FinalizarTrabajoForm(forms.ModelForm):
  class Meta:
    model = Registro
    fields = ['solucionado','observaciones','fecha_salida']
    widgets = {
            'fecha_salida': DateInput(),
            }
    
class VerificarTrabajoForm(forms.ModelForm):
  class Meta:
    model = Registro
    fields = ['verificacion','fecha_verificacion']
    widgets = {
            'fecha_verificacion': DateInput(),
            }
  
class CreatePrioridadForm(forms.ModelForm):
  class Meta:
      model = Prioridad
      fields = '__all__'
      
class CreateEquipoForm(forms.ModelForm):
  class Meta:
      model = Equipo
      fields = '__all__'

taller/views.py
from django.db.models import F, Count
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView
from django.db.models.functions import ExtractMonth
from calendar import month_name
import locale
from django.contrib.auth.decorators import login_required

from .models import Choice, Question, Registro, Prioridad, Entidad, Especialista, Equipo
from .forms import *

# Create your views here.

# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "latest_question_list"

#     def get_queryset(self):
#         """Return the last five published questions."""
#         return Question.objects.order_by("-pub_date")[:5]

@login_required(login_url="/login/")
def index(request):
    title = f'Estado general del taller'
    
    total_registro_list = (Registro.objects
          .values('entidad__nombre')  # Group by entidad
          .annotate(ecount=Count('entidad'))  # Count registers for each entidad
          .order_by('-ecount')  # Optional: Ensure correct sorting
          )[:15]
    entidad_nombres = total_registro_list.values_list('entidad__nombre', flat=True)
    entidad_nombres = list(entidad_nombres)
    ecount_values = total_registro_list.values_list('ecount', flat=True)
    ecount_values = list(ecount_values)
    
    registros_x_estado_list = (Registro.objects
          .values('estado')
          .annotate(estcount=Count('estado'))
          )
    
    estado_nombres = registros_x_estado_list.values_list('estado', flat=True)
    estado_nombres = list(estado_nombres)
    estcount_values = registros_x_estado_list.values_list('estcount', flat=True)
    estcount_values = list(estcount_values)
    
    solucionados = Registro.objects.filter(solucionado=True).count()
    no_solucionados = Registro.objects.filter(solucionado=False).count()
    total_registros = Registro.objects.count()
    
    registros_por_mes = (Registro.objects
                     .annotate(mes=ExtractMonth('fecha_entrada'))
                     .values('mes')
                     .annotate(total_registros=Count('id'))
                     .order_by('mes'))
    locale.setlocale(locale.LC_TIME, 'es_ES.utf8')
    meses_en_espanol = {i: month_name[i] for i in range(1, 13)}
    resultados_registros_por_mes = [{'mes': meses_en_espanol[registro['mes']], 'total_registros': registro['total_registros']}
                                    for registro in registros_por_mes]
    
    # total_registros_x_mes = resultados_registros_por_mes.values_list('total_registros', flat=True)
    # total_registros_x_mes = list(total_registros_x_mes)
    # meses = resultados_registros_por_mes.values_list('mes', flat=True)
    # meses = list(meses)
    
    meses = [entry['mes'] for entry in resultados_registros_por_mes]
    total_registros_x_mes = [entry['total_registros'] for entry in resultados_registros_por_mes]
    
    
    context = {
        'title': title,
        'entidades': entidad_nombres,
        'totalregistros': ecount_values,
        'estados': estado_nombres,
        'estcount': estcount_values,
        'solucionados': solucionados,
        'no_solucionados': no_solucionados,
        'total_registros': total_registros,
        'total_registros_x_mes': total_registros_x_mes,
        'meses': meses,
        }
    return render(request, 'taller/index.html', context)

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("taller:results", args=(question.id,)))


class RegistroIndexView(generic.ListView):
    model = Registro
    template_name = "taller/registro.html"
    
    # def get_queryset(self):
    #     queryset = Registro.objects.all()
    #     return queryset.order_by('fecha_entrada')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Registro de recepciones'
        return context


class PrioridadListView(generic.ListView):
    model = Prioridad
    template_name = "taller/prioridades_list.html"

class EquipoListView(generic.ListView):
    model = Equipo
    template_name = "taller/equipos_list.html"

@login_required(login_url="/login/")
def create_prioridad_view(request):
    if request.method == 'POST':
        form = CreatePrioridadForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:prioridades-list'))
    else:
        form = CreatePrioridadForm()
    context = {'form': form}
    return render(request, 'taller/create_prioridad.html', context)

@login_required(login_url="/login/")
def create_equipo_view(request):
    if request.method == 'POST':
        form = CreateEquipoForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:equipos-list'))
    else:
        form = CreateEquipoForm()
    context = {'form': form}
    return render(request, 'taller/create_equipo.html', context)

@login_required(login_url="/login/")
def create_registro_view(request):
    if request.method == 'POST':
        form = CreateRegistroForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            return HttpResponseRedirect(reverse('taller:registro'))
    else:
        form = CreateRegistroForm()
    context = {'form': form}
    return render(request, 'taller/create_registro.html', context)

@login_required(login_url="/login/")
def asignar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = AsignaTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'ASIGNADO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-asignados'))
    else:
        form = AsignaTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/asigna_trabajo.html', context)

@login_required(login_url="/login/")
def evaluar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = EvaluaTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'EN_PROCESO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-en-proceso'))
    else:
        form = EvaluaTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/evaluar_trabajo.html', context)

@login_required(login_url="/login/")
def finalizar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = FinalizarTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.estado = 'FINALIZADO'
            registro.save(update_fields=['estado'])
            return HttpResponseRedirect(reverse('taller:registro-finalizados'))
    else:
        form = FinalizarTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/finalizar_trabajo.html', context)

@login_required(login_url="/login/")
def verificar_trabajo_view(request, id):
    registro = Registro.objects.get(id=id)
    if request.method == 'POST':
        form = VerificarTrabajoForm(request.POST, instance=registro)
        if form.is_valid():
            form.save()
            registro.verificado = True
            registro.save(update_fields=['verificado'])
            return HttpResponseRedirect(reverse('taller:registro-finalizados'))
    else:
        form = VerificarTrabajoForm(instance=registro)
        
    context = {'form': form}
    return render(request, 'taller/verificar_trabajo.html', context)

@login_required(login_url="/login/")
def date_selector(request, reporte=None):
    if request.method == 'POST':
        fecha_inicial=request.POST['fecha_inicial']
        fecha_final=request.POST['fecha_final']
        if reporte == 'registro':
            title = f'Registro de recepciones desde {fecha_inicial}, hasta {fecha_inicial}'
            registro_list = Registro.objects.filter(fecha_entrada__range=(fecha_inicial, fecha_final))
            context = {
                'title': title,
                'registro_list': registro_list,
                }
            return render(request, 'taller/registro.html', context)
        
        if reporte == 'indicadores':
            title = f'indicadores {fecha_inicial}, hasta {fecha_inicial}'
            pass
        
    context = {}
    return render(request, 'wizards/date_selector.html', context)

@login_required(login_url="/login/")

taller/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" sizes="32x32" href="{% static 'images/icon.png' %}" />
  <title>Unedy - {% block title %}{% endblock %}</title>
  {% block stylesheets %}{% endblock %}
</head>
<body>
  {% block body %}{% endblock %}
  {% block javascripts %}{% endblock %}
</body>
</html>

taller/templates/footer.html
{% load static %}
<!--    Footer-->
<footer class="container-fluid bg-dark mt-3">
  <div class="row text-white py-4">
      <div class="col-md-4">
          <img src="{% static 'images/icon.png' %}" alt="UNEDY" width="150" height="auto" class="float-left mr-3">
          <!-- <h4 class="lead">UNEDY</h4> -->
          <!-- <footer class="blockquote-footer mt-2">Desarrollado por: <cite title="Source Title">Ing. Rafael Enrique Báez Guevara</cite></footer> -->
      </div>
      <div class="col-md-4">
          <h4 class="lead"><a href="#">Gestor de taller UNE</a></h4>
          <p>"UNEDY" es un utilitario gestionar los procesos de recepción y entrega en un taller de reparaciones.
          </p>
      </div>
      <div class="col-md-4">
          <h4 class="lead">Potenciado Por:</h4>
          <div>
          <a href="https://www.djangoproject.com/"><img src="{% static 'images/Django_logo.png' %}" alt="" width="120" height="auto" class="float-left mr-3"></a>
          <a href="https://getbootstrap.com/"><img src="{% static 'images/Boostrap_logo.svg' %}" alt="" width="80" height="auto" class="float-left mr-3"></a>
          <a href="https://fontawesome.com"><i class="fab fa-font-awesome fa-5x float-left align-middle mr-3"></i></a>
          <a href="https://echarts.apache.org"><img src="{% static 'images/echarts.png' %}" alt="" width="80" height="auto" class="float-left mr-3"></a>
          </div>
      </div>
  </div>
</footer>
<!--    Fin del Footer-->

taller/templates/frontend.html
{% extends "base.html" %}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'fontawesome/css/all.min.css' %}" type="text/css">
  <link rel="stylesheet" href="{% static 'fontawesome/css/svg-with-js.min.css' %}" type="text/css">
{% endblock %}

{% block javascripts %}
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'fontawesome/js/all.min.js' %}"></script>
{% endblock %}

{% block body %}
  {% include "menu.html" %}
  
  {% block content %}{% endblock %}
  
  {% include "footer.html" %}
{% endblock %}

taller/templates/menu.html
{% load static %}
<!-- Barra de navegación -->
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/icon.png' %}" width="auto" height="30" alt="Indi"> UNEDY
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link" aria-current="page" href="/"> <i class="fa fa-home" aria-hidden="true"></i> Inicio</a>
            </li>
            
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-file-pen"></i> Operaciones
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'taller:create-equipo' %}"><i class="fa fa-desktop"></i> Agregar equipo</a></li>
                    <li><a class="dropdown-item" href="{% url 'taller:create-registro' %}"><i class="fa fa-file-pen"></i> Registrar equipo</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'taller:registro-recepcionados' %}"><i class="fa fa-hand-pointer"></i> Asignar trabajo</a></li>
                    <li><a class="dropdown-item" href="{% url 'taller:registro-asignados' %}"><i class="fa fa-glasses"></i> Evaluar trabajo</a></li>
                    <li><a class="dropdown-item" href="{% url 'taller:registro-en-proceso' %}"><i class="fa fa-thumbs-up"></i> Finalizar trabajo</a></li>
                    <li><a class="dropdown-item" href="{% url 'taller:registro-finalizados' %}"><i class="fa fa-calendar-check"></i> Verificar trabajo</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa fa-file-lines" aria-hidden="true"></i> Reportes
            </a>
            <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'taller:registro' %}"><i class="fa-solid fa-pencil-alt"></i> Recepciones</a></li>
                <li><a class="dropdown-item" href="{% url 'taller:equipos-list' %}"><i class="fa-solid fa-list"></i> Listado de equipos</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="{% url 'taller:reporte-x-fecha' reporte='registro' %}"><i class="fa-solid fa-file-pdf"></i> Recepciones por fecha</a></li>
                <li><a class="dropdown-item" href="{% url 'taller:reporte-x-entidad' reporte='registro' %}"><i class="fa-solid fa-file-pdf"></i> Recepciones por entidad</a></li>
                <li><a class="dropdown-item" href="{% url 'taller:reporte-x-prioridad' reporte='registro' %}"><i class="fa-solid fa-file-pdf"></i> Recepciones por prioridad</a></li>
                <li><a class="dropdown-item" href="{% url 'taller:reporte-x-especialista' reporte='registro' %}"><i class="fa-solid fa-file-pdf"></i> Recepciones por especialista</a></li>
                <li><a class="dropdown-item" href="{% url 'taller:reporte-x-estado' reporte='registro' %}"><i class="fa-solid fa-file-pdf"></i> Recepciones por estado</a></li>
                <!-- <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href=""><i class="fa-solid fa-chart-pie"></i> Gráficas por fecha</a></li>
                <li><a class="dropdown-item" href=""><i class="fa-solid fa-chart-pie"></i> Gráficas por cliente</a></li>
                <li><a class="dropdown-item" href=""><i class="fa-solid fa-chart-pie"></i> Gráficas por fecha</a></li> -->
            </ul>
            </li>

            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Administración</a>
            </li>
            {% endif %}


            <!-- <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="fa-solid fa-shield-halved"></i> Seguridad
                </a>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="#"><i class="fa fa-key" aria-hidden="true"></i> Cambiar Contraseña</a></li>
                </ul>
            </li> -->
        </ul>


        <!-- Right links -->
        <ul class="navbar-nav ms-auto d-flex align-items-center">
            <li class="nav-item mx-2 mx-lg-1">
            <form method="post" action="{% url 'security:logout' %}">
                {% csrf_token %}
                <button type="submit"><i class="fa fa-sign-out"></i> Salir</button>
            </form>
            </li>
            <li class="nav-item mx-2 mx-lg-1">
            <span class="navbar-text">
                <i class="fa-regular fa-user"></i> {{ user.get_username }}
            </span>
            </li>
        </ul>
        <!-- Right links -->
        
        </div>
    </div>
  </nav>
  
<!-- Fin de Barra de navegación -->